# Generated by Django 3.2.7 on 2021-11-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JamTersedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KabupatenKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten_kota', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TanggalTersedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SentraVaksinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat_sentra_vaksinasi', models.TextField()),
                ('kabupaten_kota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daftar_vaksinasi.kabupatenkota')),
                ('provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daftar_vaksinasi.provinsi')),
            ],
        ),
        migrations.CreateModel(
            name='PesertaVaksinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('nik', models.CharField(max_length=50)),
                ('vaksinasi_ke', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1, null=True)),
                ('alamat_sentra_vaksinasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daftar_vaksinasi.sentravaksinasi')),
                ('jam_vaksinasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daftar_vaksinasi.jamtersedia')),
                ('tanggal_vaksinasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daftar_vaksinasi.tanggaltersedia')),
            ],
        ),
        migrations.AddField(
            model_name='kabupatenkota',
            name='provinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daftar_vaksinasi.provinsi'),
        ),
    ]
