# Generated by Django 3.2.7 on 2021-11-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamtersedia',
            name='jam',
            field=models.TimeField(),
        ),
    ]
