# Generated by Django 3.2.7 on 2021-11-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_relawan_vaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=30, verbose_name='Nama Lengkap')),
                ('umur', models.IntegerField(verbose_name='Umur')),
                ('nomor_hp', models.IntegerField(verbose_name='Nomor Hp')),
                ('nomor_ktp', models.IntegerField(verbose_name='Nomor Ktp')),
                ('email', models.EmailField(max_length=30)),
                ('foto', models.ImageField(blank=True, upload_to='images/')),
                ('alamat', models.TextField(verbose_name='Alamat domisili')),
                ('Riwayat_nakes', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, verbose_name='Apakah Anda Seorang Nakes?')),
                ('Peran', models.CharField(choices=[('Vaksinator', 'Vaksinator'), ('Screening', 'Screening'), ('Registrasi', 'Registrasi'), ('Pelaporan', 'Pelaporan')], max_length=30, verbose_name='Apa peran yang Anda inginkan?')),
            ],
        ),
    ]
