# Generated by Django 3.2.7 on 2021-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=30, verbose_name='Nama Lengkap')),
                ('BirthDate', models.DateField(verbose_name='Tanggal Lahir')),
                ('NIK', models.CharField(max_length=16, verbose_name='Nomor Induk Kependudukan (NIK)')),
                ('Goldar', models.CharField(choices=[('Pilih', 'Pilih'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default=1, max_length=5, verbose_name='Golongan Darah')),
                ('Sentra', models.CharField(max_length=30, verbose_name='Sentra Layanan Donor Darah')),
                ('Date', models.DateField(verbose_name='Tanggal Donor Darah')),
                ('Time', models.TimeField(verbose_name='Waktu Donor Darah')),
            ],
        ),
        migrations.CreateModel(
            name='NamaLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=20)),
                ('Province', models.CharField(choices=[('Aceh', 'Aceh'), ('Sumatera Utara', 'Sumatera Utara'), ('Sumatera Barat', 'Sumatera Barat'), ('Riau', 'Riau'), ('Kepulauan Riau', 'Kepulauan Riau'), ('Jambi', 'Jambi'), ('Sumatera Selatan', 'Sumatera Selatan'), ('Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung'), ('Lampung', 'Lampung'), ('DKI Jakarta', 'DKI Jakarta'), ('Bengkulu', 'Bengkulu'), ('Banten', 'Banten'), ('Jawa Barat', 'Jawa Barat'), ('Jawa Tengah', 'Jawa Tengah'), ('DI Yogyakarta', 'DI Yogyakarta'), ('Jawa Timur', 'Jawa Timur'), ('Bali', 'Bali'), ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'), ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'), ('Kalimantan Barat', 'Kalimantan Barat'), ('Kalimantan Tengah', 'Kalimantan Tengah'), ('Kalimantan Selatan', 'Kalimantan Selatan'), ('Kalimantan Timur', 'Kalimantan Timur'), ('Kalimantan Utara', 'Kalimantan Utara'), ('Sulawesi Utara', 'Sulawesi Utara'), ('Gorontalo', 'Gorontalo'), ('Sulawesi Tengah', 'Sulawesi Tengah'), ('Sulawesi Barat', 'Sulawesi Barat'), ('Sulawesi Selatan', 'Sulawesi Selatan'), ('Sulawesi Tenggara', 'Sulawesi Tenggara'), ('Maluku', 'Maluku'), ('Maluku Utara', 'Maluku Utara'), ('Papua Barat', 'Papua Barat'), ('Papua', 'Papua')], default=1, max_length=25, verbose_name='Provinsi')),
                ('Goldar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default=1, max_length=2, verbose_name='Golongan Darah')),
            ],
        ),
    ]
